---
title: "Data wrangling"
subtitle: "From [Lizard guts: Naxos](https://github.com/katekathrynkat/lizard-guts-naxos)"
output:
  katereR::t_analysis
---

**Kate Culhane**, Dept. of Ecology, Evolution, and Marine Biology, UC Santa Barbara  
[kathrynculhane@ucsb.edu](kathrynculhane@ucsb.edu)
[<i class="fa fa-github"></i>](https://github.com/katekathrynkat/)
[<i class="fa fa-twitter"></i>](https://twitter.com/katekathrynkat/)

***

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_knit$set(root.dir = '..')
knitr::opts_chunk$set(echo = TRUE, results = 'hold',
                      warning = FALSE, message = FALSE,
                      fig.width=5, fig.height=3, rows.print=5)
```

<div class = "summary">

**Summary**

Wrangling data 

</div>

***

#### Dependencies

```{r packages and data, class.source = 'fold-show'}

##### PACKAGES #####

library(tidyverse) # data manipulation & visualization

##### DATA #####

# Stomach pump invert ID (all islands)
diet_raw <- read_csv('data_raw/field/diet_field.csv')

# Site metadata (Naxos)
meta_raw <- read_csv('data_raw/field/naxos_meta.csv')

# Vegetation quadrats (Naxos)
veg_raw <- read_csv('data_raw/field/naxos_veg.csv')

# Pitfall/sticky metadata (all islands)
prey_meta_raw <- read_csv('data_raw/field/prey_meta.csv')

# Pitfall trap invert ID (all islands)
prey_p_raw <- read_csv('data_raw/field/prey_pitfall.csv')

# Sticky trap invert ID (all islands)
prey_s_raw <- read_csv('data_raw/field/prey_sticky.csv')

```

#### Output files

- **02_diet.csv**: Naxos stomach pump invert ID

## Wrangling

### Lizard diet

```{r}

diet <- diet_raw %>% 
  filter(island == "Naxos")

write_csv(diet, "output/02_diet.csv", col_names = TRUE)

```

### Available prey community

```{r}

prey_meta <- prey_meta_raw %>% 
  filter(island == "Naxos")

prey_p <- prey_p_raw %>% 
  filter(island == "Naxos") %>% 
  mutate(trap_type = "pitfall",
         sampleID = paste0("P-", site, "-", trap))

prey_s <- prey_s_raw %>% 
  filter(island == "Naxos") %>% 
  mutate(trap_type = "sticky",
         sampleID = paste0("S-", site, "-", trap))

write_csv(prey_meta, "output/02_prey_meta.csv", col_names = TRUE)
write_csv(prey_p, "output/02_prey_p.csv", col_names = TRUE)
write_csv(prey_s, "output/02_prey_s.csv", col_names = TRUE)

```


## Notes & resources

- [Webpage](link), author

<br>
<br>
<br>

<details><summary>**Session info**</summary>
```{r code}
devtools::session_info()
```
</details>

