---
title: "Data exploration"
subtitle: "From [Lizard guts: Naxos](https://github.com/katekathrynkat/lizard-guts-naxos)"
output:
  katereR::t_analysis
---

**Kate Culhane**, Dept. of Ecology, Evolution, and Marine Biology, UC Santa Barbara  
[kathrynculhane@ucsb.edu](kathrynculhane@ucsb.edu)
[<i class="fa fa-github"></i>](https://github.com/katekathrynkat/)
[<i class="fa fa-twitter"></i>](https://twitter.com/katekathrynkat/)

***

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_knit$set(root.dir='..')
knitr::opts_chunk$set(echo=TRUE, results='hold', warning=FALSE, message=FALSE,
                      fig.width=5, fig.height=3, rows.print=5)
```

<div class = "summary">

**SUMMARY**

Exploring the data

</div>

***

**DEPENDENCIES**

```{r dependencies, class.source='fold-show'}

##### PACKAGES #####

library(tidyverse) # data manipulation & visualization
library(vegan) # community analyses
library(goeveg) # scree plot for NMDS

##### DATA #####

# Invertebrate counts by order from sticky and pitfall trap samples
prey <- read_csv("output/02_prey.csv")

# Invertebrate counts by order from lizard stomach pumping samples
diet <- read_csv("output/02_diet_inverts.csv")

# Site by species matrix (invert prey data)
prey_matrix <- read_csv("output/02_prey_matrix.csv")

# Site by species matrix (diet data)
diet_matrix <- read_csv("output/02_diet_matrix.csv")

```

## Abundance by order

### Available prey community

```{r}

# Summary table
prey %>% 
  group_by(order, trap_type) %>% 
  summarise(n = sum(count)) %>% 
  pivot_wider(names_from = trap_type, values_from = n) %>% 
  mutate(total = pitfall + sticky) %>% 
  arrange(-total)

```

```{r fig.width=8, fig.height=8}

# Abundance by order
prey %>% 
  ggplot(aes(x = trap_type, y = count)) +
  geom_jitter(aes(color = trap_type),
              width = 0.1, size = 1.5) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  facet_wrap(~ fct_reorder(order, count, .fun = sum, .desc = TRUE),
             scales = "free_y") +
  theme_classic() +
  theme(legend.position = "NA") +
  labs(x = "Trap type", y = "Abundance (indv/trap)")

```

### Diet

```{r}

# Summary table
diet %>% 
  group_by(order) %>% 
  summarise(n = sum(count)) %>% 
  arrange(-n)

```

```{r fig.width=8, fig.height=5}

# Abundance by order
diet %>% 
  # Data wrangling
  group_by(order) %>% 
  mutate(n = length(count)) %>% 
  # Plot
  ggplot(aes(x = fct_reorder(order, count, .fun = sum, .desc = TRUE), y = count)) +
  geom_jitter(width = 0.1, size = 1.5) +
  geom_boxplot(fill = NA, outlier.shape = NA) +
  geom_text(aes(y = 50, label = paste("n =", n)),
            stat = "unique", angle = 90, size = 3, hjust = 0) +
  scale_y_log10() +
  theme_classic() +
  theme(legend.position = "NA",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Order", y = "Log abundance (indv/lizard)")

```

## NMDS

### Invert trap data 

```{r cache=TRUE, results='hide'}

# Wrangle matrix
m_p <- as.matrix(prey_matrix[-c(1:4)])
rownames(m_p) <- prey_matrix$sample
m_p_hell <- decostand(m_p, 'hellinger') # Hellinger transformation
m_p_meta <- select(prey_matrix, sample, site, trap, trap_type) # metadata

# Scree plot to check stress per number of dimensions
dimcheckMDS(m_p_hell, distance = "bray", autotransform = FALSE, k = 10)

```

```{r cache=TRUE, class.source='fold-show'}

# Create NMDS ordination
ord <- metaMDS(m_p_hell,
               distance = 'bray', # use Bray-Curtis distances
               autotransform = FALSE, # already manually transformed the matrix
               k = 3, # number of dimensions
               trymax = 1000)

# Stress plot
stressplot(ord)

```

```{r fig.width=8, fig.height=6}

# Plot ordination
scale_trap <- c("red", "orange")
names(scale_trap) <- c("pitfall", "sticky")
par(mar = c(4,4,1,1))
plot(ord, display = 'sites', type = 'n')
points(ord, display = 'sites', pch = 19, col = scale_trap[m_p_meta$trap_type])
ordiellipse(ord, groups = m_p_meta$trap_type,
            label = TRUE, col = scale_trap, lwd = 2)
text(ord, display = 'species')

```

Number of dimenstions = `r ord$ndim`

Stress = `r round(ord$stress,3)`

## Notes & resources

<br>
<br>
<br>

<details><summary>**Session info**</summary>
```{r session-info}
devtools::session_info()
```
</details>
